// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA8J63wtoZ7DoJ0lzCHpJsxwUJrx3evTA',
    appId: '1:494823218724:web:954aad10e17f6c225102b1',
    messagingSenderId: '494823218724',
    projectId: 'prathima-91088',
    authDomain: 'prathima-91088.firebaseapp.com',
    storageBucket: 'prathima-91088.appspot.com',
    measurementId: 'G-BFCD091XNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmi2OyMtCKXqxZPqTvk1fwj3uINzlE3aE',
    appId: '1:494823218724:android:7d2c4e7fe46f5bd55102b1',
    messagingSenderId: '494823218724',
    projectId: 'prathima-91088',
    storageBucket: 'prathima-91088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPmNr49TkEVwapPopSTkCuzfyUMgwY9cA',
    appId: '1:494823218724:ios:aedf813a2aa8b4265102b1',
    messagingSenderId: '494823218724',
    projectId: 'prathima-91088',
    storageBucket: 'prathima-91088.appspot.com',
    iosBundleId: 'com.example.prathimaLoanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPmNr49TkEVwapPopSTkCuzfyUMgwY9cA',
    appId: '1:494823218724:ios:aedf813a2aa8b4265102b1',
    messagingSenderId: '494823218724',
    projectId: 'prathima-91088',
    storageBucket: 'prathima-91088.appspot.com',
    iosBundleId: 'com.example.prathimaLoanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA8J63wtoZ7DoJ0lzCHpJsxwUJrx3evTA',
    appId: '1:494823218724:web:5050aac78edc17125102b1',
    messagingSenderId: '494823218724',
    projectId: 'prathima-91088',
    authDomain: 'prathima-91088.firebaseapp.com',
    storageBucket: 'prathima-91088.appspot.com',
    measurementId: 'G-722P70J422',
  );

}